import { BuiltinMask } from "./typing";
import { ModelProvider } from "../constant";

export const CN_MASKS: BuiltinMask[] = [
  {
    avatar: "1f47d",
    name: "gpt-3.5-turbo",
    context: [],
    modelConfig: {
      model: "gpt-3.5-turbo",
      provider: ModelProvider.OpenAi,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 1000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1688899480510,
  },
  {
    avatar: "1f60e",
    name: "gpt-4-turbo-preview",
    context: [],
    modelConfig: {
      model: "gpt-4-turbo-preview",
      provider: ModelProvider.OpenAi,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1688899480510,
  },
  {
    avatar: "1f60e",
    name: "gpt-4o",
    context: [],
    modelConfig: {
      model: "gpt-4o",
      provider: ModelProvider.OpenAi,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1688899480510,
  },
  {
    avatar: "1f47f",
    name: "llama2_tog",
    context: [],
    modelConfig: {
      model: "meta-llama/Llama-2-70b-chat-hf",
      provider: ModelProvider.Togeter,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f47f",
    name: "llama3",
    context: [],
    modelConfig: {
      model: "meta-llama/Llama-3-70b-chat-hf",
      provider: ModelProvider.ANYSCALE,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f47a",
    name: "Claude 3 haiku",
    context: [],
    modelConfig: {
      model: "claude-3-haiku-20240307",
      provider: ModelProvider.CLAUDE,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f479",
    name: "Claude 3 Sonnet",
    context: [],
    modelConfig: {
      model: "claude-3-sonnet-20240229",
      provider: ModelProvider.CLAUDE,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "Claude 3 Opus",
    context: [],
    modelConfig: {
      model: "claude-3-opus-20240229",
      provider: ModelProvider.CLAUDE,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "Claude 3 Opus",
    context: [],
    modelConfig: {
      model: "claude-3-opus-20240229",
      provider: ModelProvider.CLAUDE,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "Claude 3 Opus",
    context: [],
    modelConfig: {
      model: "claude-3-opus-20240229",
      provider: ModelProvider.CLAUDE,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "MythoMax",
    context: [],
    modelConfig: {
      model: "Gryphe/MythoMax-L2-13b",
      provider: ModelProvider.Togeter,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "upstage_solar",
    context: [],
    modelConfig: {
      model: "upstage/SOLAR-10.7B-Instruct-v1.0",
      provider: ModelProvider.Togeter,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "wizardlm",
    context: [],
    modelConfig: {
      model: "WizardLM/WizardLM-13B-V1.2",
      provider: ModelProvider.Togeter,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "nousHermes",
    context: [],
    modelConfig: {
      model: "NousResearch/Nous-Hermes-2-Mistral-7B-DPO",
      provider: ModelProvider.Togeter,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
  {
    avatar: "1f921",
    name: "openhermes",
    context: [],
    modelConfig: {
      model: "teknium/OpenHermes-2p5-Mistral-7B",
      provider: ModelProvider.Togeter,
      temperature: 0.5,
      max_tokens: 2000,
      presence_penalty: 0,
      sendMemory: true,
      historyMessageCount: 4,
      compressMessageLengthThreshold: 2000,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1700713360000,
  },
];
